"""Convert somil.jpeg into the ASCII portrait used in the hero (src/lib/portrait.ts).

Usage (one-off, in any venv):
    pip install "rembg[cpu]" opencv-python-headless pillow
    python scripts/ascii-portrait.py

Steps: remove the background (rembg, human segmentation model), crop to head and
shoulders, boost local contrast (CLAHE), downsample to a character grid, and map
brightness onto a character ramp. Two variants are written: bright-is-dense for the
dark theme and dark-is-dense for the light theme.
"""

import json
from pathlib import Path

import cv2
import numpy as np
from PIL import Image
from rembg import new_session, remove

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "somil.jpeg"
OUT = ROOT / "src/lib/portrait.ts"

COLS = 100
CROP = (200, 360, 760, 1000)  # x0, y0, x1, y1 in source pixels: head and shoulders
CELL = 1 / 0.6  # cell height / width for a mono font at line-height 1
RAMP = " .'`,:;!il1tfjLCGO08&@"  # sparse -> dense; index 0 is reserved for background

rgba = np.array(remove(Image.open(SOURCE).convert("RGB"), session=new_session("u2net_human_seg")))
x0, y0, x1, y1 = CROP
rgba = rgba[y0:y1, x0:x1]
alpha = rgba[..., 3].astype(np.float32) / 255
gray = cv2.cvtColor(np.ascontiguousarray(rgba[..., :3]), cv2.COLOR_RGB2GRAY)
gray = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(6, 6)).apply(gray)

h, w = gray.shape
rows = round(COLS * h / w / CELL)
small = cv2.resize(gray, (COLS, rows), interpolation=cv2.INTER_AREA).astype(np.float32) / 255
mask = cv2.resize(alpha, (COLS, rows), interpolation=cv2.INTER_AREA) >= 0.45

# Drop empty rows above and below the subject.
filled = np.flatnonzero(mask.any(axis=1))
small, mask = small[filled[0] : filled[-1] + 1], mask[filled[0] : filled[-1] + 1]
rows = len(small)

# Stretch the subject's tonal range across the whole ramp.
lo, hi = np.percentile(small[mask], [2, 98])
small = np.clip((small - lo) / (hi - lo), 0, 1)


def render(invert: bool) -> str:
    lines = []
    for y in range(rows):
        line = ""
        for x in range(COLS):
            if not mask[y, x]:
                line += " "
                continue
            v = 1 - small[y, x] if invert else small[y, x] ** 0.8
            line += RAMP[1 + min(len(RAMP) - 2, int(v * (len(RAMP) - 1)))]
        lines.append(line.rstrip())
    return "\n".join(lines)


OUT.write_text(
    "// Generated by scripts/ascii-portrait.py from somil.jpeg. Do not edit by hand.\n"
    f"export const portraitCols = {COLS};\n"
    f"export const portraitRows = {rows};\n"
    f"export const portraitDark = {json.dumps(render(False))};\n"
    f"export const portraitLight = {json.dumps(render(True))};\n"
)
print(f"wrote {OUT.relative_to(ROOT)} ({COLS}x{rows})")
